---
title: "Final Project"
author: "Group M"
date: "2023-04-30"
output: pdf_document
---

```{r setup, include=FALSE,echo = FALSE}
# knitr::opts_knit$set(root.dir = '<Your directory>')
library(igraph)
library(network)
library(statnet)
library(sna)
library(intergraph)
library(RColorBrewer)

library(ergm)
```

# Read the data
```{r}
# read the edgelist3.csv
hiv_edges <- read.csv("edgelist_cleaned.csv", header = T, stringsAsFactors = F)

# read the nodes3 CSV file
hiv_nodes <- read.csv("nodes_cleaned.csv", header = T, stringsAsFactors = F)

# creae a network, directed, weighted, with edgelist
hiv_net <- network(hiv_edges, matrix.type="edgelist",directed = T, loops = T)

```

# Plot
```{r plot2, cache=TRUE}
plot(hiv_net, vertex.col = 'red', displaylabels = F,vertex.cex = 0.7)
```

# five-number summary
```{r}
network.size(hiv_net) # find the size value
gden(hiv_net) # find the density
components(hiv_net) # Components
diameter( asIgraph (hiv_net) ) # find the diameter
gtrans(hiv_net,mode="graph") # find the clustering coefficient
```

```{r}
# Ensure that the node IDs in the network object match the order in the hiv_nodes dataframe
hiv_net %v% "ID" <- as.character(hiv_nodes$ID)

# Assign node attributes to the hiv_net network object
hiv_net %v% "RACE" <- hiv_nodes$RACE
hiv_net %v% "SEX" <- hiv_nodes$SEX
hiv_net %v% "BEHAV" <- hiv_nodes$BEHAV
hiv_net %v% "AGE" <- hiv_nodes$AGE
hiv_net %v% "DISABLE" <- hiv_nodes$DISABLE
hiv_net %v% "UNEMP" <- hiv_nodes$UNEMP
hiv_net %v% "STREETS" <- hiv_nodes$STREETS
hiv_net %v% "EDUC" <- hiv_nodes$EDUC

```

```{r}
summary(hiv_net,print.adj=FALSE)
```

# centrality measure
```{r}
# Out-degree centrality
out_degree_centrality <- igraph::degree(asIgraph (hiv_net), mode="out")

# Betweenness centrality
betweenness_centrality <- igraph::betweenness(asIgraph (hiv_net), directed = TRUE, normalized = TRUE)

# Eigenvector centrality
eigenvector_centrality <- igraph::evcent(asIgraph (hiv_net), directed = TRUE)$vector

hiv_nodes$DegreeCentrality <- out_degree_centrality
hiv_nodes$BetweennessCentrality <- betweenness_centrality
hiv_nodes$EigenvectorCentrality <- eigenvector_centrality

attributes <- c("RACE", "SEX", "BEHAV", "AGE", "DISABLE", "UNEMP", "STREETS", "EDUC")
centrality_measures <- c("DegreeCentrality", "BetweennessCentrality", "EigenvectorCentrality")

for (attr in attributes) {
  cat("Centrality measures for", attr, ":\n")
  cat("---------------------------\n")
  attribute_groups <- split(hiv_nodes, hiv_nodes[[attr]])
  for (group in names(attribute_groups)) {
    cat("Group", group, ":\n")
    cat("  Mean Degree Centrality: ", mean(attribute_groups[[group]]$DegreeCentrality), "\n")
    cat("  Mean Betweenness Centrality: ", mean(attribute_groups[[group]]$BetweennessCentrality), "\n")
    cat("  Mean Eigenvector Centrality: ", mean(attribute_groups[[group]]$EigenvectorCentrality), "\n\n")
  }
  cat("\n")
}


```

# community detection
```{r}
# Community detection using infomap method 
set.seed(123)
hiv_net_ig <- asIgraph(hiv_net)
community <- igraph::cluster_infomap(hiv_net_ig , e.weights = E(hiv_net_ig)$Weight)
V(hiv_net_ig)$community <- membership(community)

communities <- unique(V(hiv_net_ig)$community)
community_summary <- data.frame(community = communities,
                                avg_in_degree = length(communities),
                                avg_out_degree = length(communities),
                                avg_edge_weight = length(communities))

for (comm in communities) {
  nodes_in_community <- which(V(hiv_net_ig)$community == comm)
  
  community_subgraph <- induced_subgraph(hiv_net_ig, nodes_in_community)
  
  community_summary[comm, "avg_in_degree"] <- mean(igraph::degree(community_subgraph, mode = "in"))
  community_summary[comm, "avg_out_degree"] <- mean(igraph::degree(community_subgraph, mode = "out"))
  
  edge_weights <- E(community_subgraph)$Weight
  community_summary[comm, "avg_edge_weight"] <- mean(edge_weights)
}

# Sort the data frame by the average in-degree, average out-degree, and average edge weight
community_summary_sorted <- community_summary[order(community_summary$avg_in_degree, community_summary$avg_out_degree, community_summary$avg_edge_weight, decreasing=TRUE), ]

# Print the top 10 communities
print(community_summary_sorted[1:10, ])
```

# characteristics of the top 10 communities

```{r}
# Get the top 10 communities
top_communities <- community_summary_sorted[1:10, "community"]

# Define a function to calculate proportions of each attribute
attribute_proportions <- function(attribute, community_nodes) {
  attribute_values <- vertex_attr(hiv_net_ig, attribute, index = V(hiv_net_ig))[community_nodes]
  prop_table <- prop.table(table(attribute_values))
  return(prop_table)
}

# Create a data frame to store the proportions of each attribute in each community
attributes <- c("RACE", "SEX", "BEHAV", "AGE", "DISABLE", "UNEMP", "STREETS", "EDUC")
top_community_characteristics <- data.frame(community = numeric(),
                                            attribute = character(),
                                            category = character(),
                                            proportion = numeric())

# Calculate the proportions for each attribute in each top community
for (comm in top_communities) {
  nodes_in_community <- c(which(V(hiv_net_ig)$community == comm))
  
  for (attr in attributes) {
    prop_table <- attribute_proportions(attr, nodes_in_community)
    max_prop <- max(prop_table)
    max_prop_category <- names(prop_table)[which.max(prop_table)]
    
    new_row <- data.frame(community = comm,
                          attribute = attr,
                          category = max_prop_category,
                          proportion = max_prop)
    
    top_community_characteristics <- rbind(top_community_characteristics, new_row)
  }
}

print(top_community_characteristics)

```

```{r,results='hide'}
library(tidyr)
library(dplyr)

# Reshape the data frame to have one row per community and attribute category
wide_top_community_characteristics <- top_community_characteristics %>%
  pivot_wider(names_from = attribute, values_from = c(category, proportion), names_sep = "_",
              names_glue = "{attribute}_{.value}") %>%
  select(community, matches("cate"), matches("prop"))

print(wide_top_community_characteristics)

```

# ERGM
```{r, warning=FALSE}
# null model
null_model <- ergm(hiv_net ~ edges)
summary(null_model) 
```
```{r,cache=TRUE}
reciprocity_model <- ergm(hiv_net ~ edges + mutual)
summary(reciprocity_model)
```
```{r}
# Fit an ERGM with the selected node attributes
full_model <- ergm(hiv_net ~ edges + nodematch("RACE") + nodematch("SEX") + nodematch("BEHAV") + nodematch("AGE") + nodematch("DISABLE") + nodematch("UNEMP") + nodematch("STREETS") + nodematch("EDUC"), control = control.ergm(MCMC.burnin = 5000, MCMC.interval = 1000))

summary(full_model)
```

```{r}
# Extract the coefficients from the ERGM fit
coefficients_full <- coef(full_model)

# Sort the coefficients by their absolute values to determine the strongest impact on network formation and HIV transmission
sorted_coefficients_full <- coefficients_full[order(abs(coefficients_full), decreasing = TRUE)]

print(sorted_coefficients_full)
```
# predictive model
```{r}
in_degree <- igraph::degree(hiv_net_ig, mode = "in")
dens <- density(in_degree)
cumulative_density <- cumsum(dens$y)/sum(dens$y)
threshold <- dens$x[which.min(abs(cumulative_density-0.5))]
hist(in_degree,freq=F)
abline(v = threshold, col = "red")

```

```{r}
in_degree_binary <- ifelse(in_degree >= threshold, 1, 0)

# Create a data frame with the in_degree_binary and hiv_nodes
hiv_nodes_df <- hiv_nodes
hiv_nodes_df$in_degree <- in_degree_binary
hiv_nodes_df
```
```{r}
# Load the "caret" package for model training
library(caret)
library(ggplot2)

# Prepare the data for training and testing
set.seed(123)
trainIndex <- createDataPartition(hiv_nodes_df$in_degree, p = 0.7, list = FALSE)
trainData <- hiv_nodes_df[trainIndex, ]
testData <- hiv_nodes_df[-trainIndex, ]

# Create a logistic regression model using the glm() function
model <- glm(in_degree ~ .- ID, data = trainData, family = "binomial")

# Print the model summary
summary(model)
```
```{r}
# Overall, the model indicates that BetweennessCentrality and EigenvectorCentrality are significantly associated with in_degree, as they have p-values less than 0.05. The other predictor variables do not appear to have a significant effect on in_degree.
```

# k-shell decomposition
```{r}
# Calculate k-shell values for each node
k_shells <- coreness(hiv_net_ig)
V(hiv_net_ig)$k_shell <- k_shells

# Find the maximum k-shell value
max_k_shell <- max(k_shells)

# Extract the nodes with the highest k-shell value
key_individuals_k_shell <- V(hiv_net_ig)[k_shell == max_k_shell]

# Print the key individuals
print(key_individuals_k_shell)

```

# snowball sampling
```{r}
# Start with a seed node (choose a node ID from your dataset)
seed_node <- 1

# Define the number of steps (depth) for the snowball sampling
steps <- 2

# Perform snowball sampling
snowball_sample <- igraph::neighborhood(hiv_net_ig, order = steps, nodes = seed_node, mode = "all")

# Extract the nodes in the snowball sample
key_individuals_snowball <- V(hiv_net_ig)[snowball_sample[[1]]]

# Print the key individuals
print(key_individuals_snowball)

```
# Burt's constraint
```{r}
# Calculate Burt's constraint for each node
burt_constraint <- igraph::constraint(hiv_net_ig, nodes = V(hiv_net_ig), weights = E(hiv_net_ig)$Weight)
V(hiv_net_ig)$constraint <- burt_constraint

# Create a data frame with node attributes and Burt's constraint values
node_attributes_and_constraint <- data.frame(node_id = as.vector(V(hiv_net_ig)),
                                             RACE = V(hiv_net_ig)$RACE,
                                             SEX = V(hiv_net_ig)$SEX,
                                             BEHAV = V(hiv_net_ig)$BEHAV,
                                             AGE = V(hiv_net_ig)$AGE,
                                             DISABLE = V(hiv_net_ig)$DISABLE,
                                             UNEMP = V(hiv_net_ig)$UNEMP,
                                             STREETS = V(hiv_net_ig)$STREETS,
                                             EDUC = V(hiv_net_ig)$EDUC,
                                             constraint = burt_constraint)


# Print the data frame
print(node_attributes_and_constraint)

```
```{r}
# Find the nodes with the lowest constraint values (top brokers)
top_brokers <- head(node_attributes_and_constraint[order(node_attributes_and_constraint$constraint), ], n = 10)

# Print the top brokers
print(top_brokers)
```



